### ISSUE TITLE
Columns are given the wrong headers if mapped out of order

### ISSUE THREAD

**Issue by simonwo** [register-dynamics/data-import#20]
With the [uk-tariff-2021-01-01--v4.0.246--commodities-report.xlsx](https://github.com/user-attachments/files/16785822/uk-tariff-2021-01-01--v4.0.246--commodities-report.xlsx) file, if I upload this file, and then select the following mapping:

![image](https://github.com/user-attachments/assets/0fe28730-7b47-4f81-ac2c-2bb909328d10)

The resulting data is displayed against the wrong column headings:

![image](https://github.com/user-attachments/assets/e9da3b91-5ccc-4d58-989a-8d91c6b2d6c8)

"LIVE ANIMALS" should appear in the Name column.

**Comment by rossjones** [comment]
@alaric-rd here's a test case for you :D

**Comment by simonwo** [comment]
Fixed by #22.
