### ISSUE TITLE
Table visual selection disappears when table loses focus.

### ISSUE THREAD

**Issue by rossjones** [register-dynamics/data-import#27]
When using the table and selecting a range, the table visually shows the selected area.

If the user then clicks a button outside of the table, the visual representation of the selection disappears from the table, perhaps giving the user the impression that the selection was lost.

We should find a way to ensure the visual selection isn't lost whenever another element is focused even though functionally the selection has been picked up.

**Comment by simonwo** [comment]
> I think that was by design for the original selection – the same way that clicking out of a text area removes the selection
> So we maybe need to put selection into some sort of persistent mode for selecting headers and footers
