### ISSUE TITLE
Date and time values are shown as large floats

### ISSUE THREAD

**Issue by simonwo** [register-dynamics/data-import#35]
Date and time values are shown as large floats. I think this is the common Excel date format which we probably need to do some proper formatting of. 

![image](https://github.com/user-attachments/assets/c164a038-38ac-4db0-b3c0-3bdb74d9c231)

This was generated from this sheet:
![image](https://github.com/user-attachments/assets/f2aeccf0-632c-4d4e-9d74-1fc1e9d18e8a)

**Comment by alaric-rd** [comment]
This will probably have to wait until we develop such notions as "types", which are currently completely absent from the system

**Comment by simonwo** [comment]
I think we can do better than this without having a full type system. Even if we just keep the JS native types for now and choose sensible formats for them when we get to the page, that should at least replace the numbers with date-looking things.
