### ISSUE TITLE
Merged cells are unhandled

### ISSUE THREAD

**Issue by simonwo** [register-dynamics/data-import#36]
The top row of this sheet is actually a merged cell spanning all of the columns.

![image](https://github.com/user-attachments/assets/c164a038-38ac-4db0-b3c0-3bdb74d9c231)

We should show merged cells as they appear in the original sheet with appropriate colspans (or rowspans?)

**Comment by alaric-rd** [comment]
I still need to do the range selection work before this is done!

**Comment by simonwo** [comment]
So what is the status? Is it that we can now extract cell merges but don't display them? E.g. I'm seeing merged cells being represented with extra empty cells in the tribbles sheet.

**Comment by alaric-rd** [comment]
That's right. Until I get the range selection JS working with it, I've disabled it in the code (see https://github.com/register-dynamics/data-import/blob/main/lib/importer/sheets.js#L24 for where) so I can get the extensive refactorings required to make it work merged (it was starting to collide with stuff Ross was doing). Feel free to turn that flag back on to see the cells, but then don't be shocked if range selections go all screwy on rows with merged cells in!
