### ISSUE TITLE
Blank cells at the end of rows don't appear

### ISSUE THREAD

**Issue by simonwo** [register-dynamics/data-import#37]
In this sheet, the final column on rows 3, 5, 7 and 8 are blank. No cell is generated for them in the HTML which leads to a weird looking jagged sheet. 

![image](https://github.com/user-attachments/assets/c164a038-38ac-4db0-b3c0-3bdb74d9c231)

Probably we should be generating empty cells to make the sheet span the length of the longest row.

**Comment by alaric-rd** [comment]
Fix in https://github.com/register-dynamics/data-import/pull/40
