### ISSUE TITLE
Data review shows more rows than exist

### ISSUE THREAD

**Issue by simonwo** [register-dynamics/data-import#38]
In situations where the number of rows is less than the maximum preview, blank rows are shown instead.

![image](https://github.com/user-attachments/assets/eaed7219-006b-4f6c-a0f1-63831199caf5)

We probably should limit the number of displayed rows to just the ones that are actually present, to not suggest that the user is importing blank rows.

**Comment by alaric-rd** [comment]
![image](https://github.com/user-attachments/assets/9081cdce-c45e-4f63-a91e-69e308c56516)

I can't recreate this, it just shows the actual rows for me. Please can I have a copy of your source spreadsheet so I can try to recreate it?

**Comment by alaric-rd** [comment]
Ok, I have a fix for this! It does log the ignored blank rows as "warnings" from the backend, which the frontend currently has no interest in displaying (and which aren't very interesting at all right now), but one day we'll need to think about how to display warnings and errors.

**Comment by alaric-rd** [comment]
Fix in https://github.com/register-dynamics/data-import/pull/39
