### ISSUE TITLE
Examples are shown from outside the data range

### ISSUE THREAD

**Issue by simonwo** [register-dynamics/data-import#50]
If I select a header range that is below the top line:
![image](https://github.com/user-attachments/assets/3b0f040f-6d22-402e-a4d3-1f2d3b1848c3)
In the examples, I can see values in that column from above the header line, and including the header line itself:
![image](https://github.com/user-attachments/assets/2538864e-e87a-4495-9891-918d4d8289f6)
Anything including or above the header line should not be visible in the examples.

**Comment by alaric-rd** [comment]
I suspect the problem is here:

https://github.com/register-dynamics/data-import/pull/47/files#diff-5c14057f7e0f3157e5301115432cd869f44cf31ac45584623c8c27d6c7f85796R53

...it needs to call `SessionSuggestDataRange` to get the correct range

**Comment by alaric-rd** [comment]
Fix in https://github.com/register-dynamics/data-import/pull/51
